# Ekstraksi fitur TFID berita

In [1]:
import pandas as pd

# Load data from pta_manajemen.csv
df = pd.read_csv('hasil_preprocessing_berita.csv')

In [2]:
# Display basic information about the dataset
print("Dataset shape:", df.shape)
df

Dataset shape: (3653, 3)

,isi_berita,hasil_preprocessing,kategori
0,"SURABAYA, BANGSAONLINE.com- Kejari Tanjung Per...","['kejar', 'tanjung', 'perak', 'surabaya', 'gel...",Jatim
1,"KOTA PASURUAN,BANGSAONLINE.com- Suasana Pasar ...","['kota', 'pasuruanbangsaonlinecom', 'suasana',...",Jatim
2,"TUBAN, BANGSAONLINE.com- Satreskrim Polres Tub...","['satreskrim', 'polres', 'tuban', 'kembali', '...",Jatim
3,"SIDOARJO,BANGSAONLINE.com- Program TNI Manungg...","['program', 'tni', 'manunggal', 'bangun', 'des...",Jatim
4,"GRESIK,BANGSAONLINE.com- Bupati Gresik, Fandi ...","['bupati', 'gresik', 'fandi', 'akhmad', 'yani'...",Jatim
...,...,...,...
3648,"SURABAYA, BANGSAONLINE.com- Hari ini Kota Sura...","['kota', 'surabaya', 'genap', 'usia', 'riah', ...",Komunitas dan Lingkungan
3649,"JEMBER, BANGSAONLINE.com- Serikat Nelayan Nahd...","['serikat', 'nelayan', 'nahdlatul', 'ulama', '...",Komunitas dan Lingkungan
3650,"GRESIK, BANGSAONLINE.com- Yayasan Lembaga Bant...","['yayasan', 'lembaga', 'bantu', 'hukum', 'faja...",Komunitas dan Lingkungan
3651,"PAMEKASAN, BANGSAONLINE.com- Kader dari Pameka...","['kader', 'pamekasan', 'moh', 'sai', 'yusuf', ...",Komunitas dan Lingkungan
3652,"KOTA PASURUAN, BANGSAONLINE.com- Wali Kota Pas...","['kota', 'pasuruan', 'bangsaonlinecom', 'wali'...",Komunitas dan Lingkungan

##  Ekstraksi Fitur TF-IDF

In [3]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

In [4]:
# Kolom teks hasil preprocessing
texts = df["hasil_preprocessing"].astype(str)

# Kalau ada kolom label
labels = df["kategori"]

##  TF-IDF Vectorization

In [5]:
vectorizer = TfidfVectorizer()

# Fit & transform ke matriks TF-IDF
tfidf_matrix = vectorizer.fit_transform(texts)

# Konversi ke DataFrame agar lebih mudah dibaca
tfidf_df = pd.DataFrame(
    tfidf_matrix.toarray(),
    columns=vectorizer.get_feature_names_out()
)

# Tambahkan kolom label
tfidf_df["kategori"] = labels.values

In [6]:
print("Ukuran matriks TF-IDF:", tfidf_df.shape)
tfidf_df

Ukuran matriks TF-IDF: (3653, 41081)

,aa,aaa,aab,aakan,aalamiin,aali,aalihatun,aalihi,aam,aamana,...,zuniaiti,zunuhumulfazaulakbaru,zunuubii,zurain,zuroh,zurqoni,zusvina,zwitsal,zywoo,zzegerius
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3648,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3649,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3650,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3651,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3652,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
# Simpan ke file CSV
output_file_csv = "hasil_tfidf_berita.csv"
tfidf_df.to_csv(output_file_csv, index=False)

print(f"Hasil TF-IDF berhasil disimpan ke file: {output_file_csv}")

Hasil TF-IDF berhasil disimpan ke file: hasil_tfidf_berita.csv